# SPDX-License-Identifier: LGPL-2.1-or-later
# Every third-party action in the workflows is pinned by commit; this is what
# moves those pins, one reviewed pull request at a time. LibreSCRS/ci is left
# out: its commit has to be the same in every LibreSCRS repository, so it moves
# with the release train, not one repository at a time.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
    ignore:
      - dependency-name: 'LibreSCRS/ci*'
